### ISSUE TITLE
Feature Proposal - Collapsible Dropdown Menus in Sidebar

### ISSUE THREAD

**Issue by vr-varad** [metacall/landing-page#10]
Description:
Add functionality to collapse expanded sidebar dropdown menus by clicking the header again, improving overall navigation visibility.

Current Behavior:
Dropdown menus expand but cannot be collapsed without selecting another header.

Desired Behavior:
Allow users to collapse an expanded dropdown menu by clicking its header.

Implementation Suggestions:

Introduce a toggle mechanism for dropdown menu headers.
Provide visual cues for expand/collapse states.
Benefits:

Improved visibility of sidebar elements.
Streamlined navigation experience.

**Comment by vr-varad** [comment]
@viferge I would like to work on it

**Comment by viferga** [comment]
Mmmm I think instead of adding cosmetic changes it would be cool to add more documentation to the site. For example in the original versions we used to include metacall/faq repository as another page of this website but it is not present anymore. This would be a nice feature you can add.

Anything that adds useful content like this may be more interesting than just cosmetic changes.

What do you think about it @vr-varad ?

**Comment by viferga** [comment]
Yes, go ahead, the ideal would be to automatically update the FAQ with this one: https://github.com/metacall/faq/blob/master/README.md

Similarly to what we do with the API reference with Doxygen, which gets pushed directly into the `gh-pages` branch.

Maybe it's too complex... and we can find an alternative way of adding it. There's js libs that let you link readme files directly in HTML for dynamically render them, this can be another option. This is an example of what I mean: https://marked.js.org/

Do you mind if I close this issue? You can create a new one related to the new topic if you want.

**Comment by vr-varad** [comment]
@viferga ya sure I will create a pr will the faq section and will proceed with the following things
